#!/usr/bin/env groovy

pipeline {

    agent {
        label 'jenkins-slave-node'
    }
    stages {
        stage('Compile') {
            steps {
                script {
                    dir("Day5/demo") {
                        sh "mvn clean compile"
                    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                     dir("Day5/demo") {
                        sh "mvn test"
                     }
                }
            }
        }
        stage('package') {
            steps {
                script {
                    dir("Day5/demo") {
                        sh "mvn package"
                    }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day5/demo") {
                        sh "mvn install"
                    }
                }
            }
        }
    }
}
